/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from "@adonisjs/lucid/orm";
import type { DateTime } from "luxon";

export class UserSchema extends BaseModel {
  static $columns = [
    "createdAt",
    "email",
    "fullName",
    "id",
    "role",
    "supabaseUserId",
    "updatedAt",
  ] as const;
  $columns = UserSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime;
  @column()
  declare email: string;
  @column()
  declare fullName: string | null;
  @column({ isPrimary: true })
  declare id: number;
  @column()
  declare role: string;
  @column()
  declare supabaseUserId: string | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}
